### ISSUE TITLE
[Feature request] add docker-compose.yml file

### ISSUE THREAD

**Issue by erickyun** [bunnykek/MultiUpload#4]
Hi,

I would appreciate if you could please add docker-compose.yml file.
I count on your kind consideration of my request.
I appreciate your work sir. 🙂

**Comment by bunnykek** [comment]
There is dockerfile alright provided in the repository. Why would you need docker compose file?
Simply google how to build and run a dockerfile.

**Comment by erickyun** [comment]
> There is dockerfile alright provided in the repository. Why would you need docker compose file? Simply google how to build and run a dockerfile.

İt's my suggestion sir. İf you like the idea I would appreciate if you could please add it in your repo? 👍🙂

Also `go-ul_linux_x64` needs to be set as `go-ul_x64` in order to give the right permission. https://github.com/bunnykek/MultiUpload/blob/db2038bdf81eb4d46971a6e858f5d5807b12736e/start.sh#L1

docker-compose.yml
```
version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure

```

cmd for build: `sudo docker-compose up --build`

**Comment by bunnykek** [comment]
Alright

**Comment by erickyun** [comment]
> Alright

I opened PR
